Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
ClassAndModuleChildren:
  EnforcedStyle: compact
AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'app/channels/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
