version: '3.7'
services:
  postgres:
    image: postgres:12-alpine

  web:
    build: .
    volumes:
      - .:/home
    ports:
      - 80:3000
    command: rails s -b 0.0.0.0 -p 3000
    depends_on:
      - postgres
