version: '3.7'
services:
  postgres:
    image: postgres:12-alpine

  web:
    build: .
    restart: always
    volumes:
      - .:/home
    ports:
      - 80:3000
    command: bash -c "bin/setup && rails s -b 0.0.0.0 -p 3000"
    depends_on:
      - postgres
