default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: iot_panel_development

test:
  <<: *default
  database: iot_panel_test

production:
  <<: *default
  database: iot_panel_production
